=== yogreen/webcontent/src/META-INF/configs/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://com.websystem.xml/schema"
	xmlns:tns="http://com.websystem.xml/schema" elementFormDefault="qualified">

    <complexType name="hostType">
   		 <simpleContent>
      		 <extension base="string">
    			<attribute name="master" type="boolean" default="false"/>
    			<attribute name="port" type="int" default="0"/>
    			<attribute name="name" type="string"/>
       		</extension>
   		 </simpleContent>
   		
    </complexType>
    <element name="host" type="tns:hostType">
       
    </element>
    <element name="multicast">
       <complexType>
         <attribute name="ip" type="string"></attribute>
         <attribute name="port" type="int"></attribute>
       </complexType>
    </element>
    <element name="naming">
       <complexType>
         <sequence>
            <element ref="tns:host" minOccurs="1" maxOccurs="unbounded"/>
         </sequence>
       </complexType>
       <unique name="namingUnique">
       <selector xpath="tns:host"></selector>
       <field xpath="@name"></field>
       </unique>
    </element>
    <element name="entry">
       <complexType>
         <sequence>
            <element ref="tns:host" minOccurs="1" maxOccurs="unbounded"/>
         </sequence>
         <attribute name="name" type="string" use="required"></attribute>
       </complexType>
       <unique name="hostUnique">
       <selector xpath="tns:host"></selector>
       <field xpath="@name"></field>
       </unique>
    </element>
    <element name="servers">
      <complexType>
         <sequence>
            <element ref="tns:multicast" minOccurs="0" maxOccurs="1"></element>
            <element ref="tns:naming" minOccurs="0" maxOccurs="unbounded"></element>
            <element ref="tns:entry" minOccurs="0" maxOccurs="unbounded"></element>
         </sequence>
      <attribute name="subject" type="string"/>
      </complexType>
      <unique name="entryUnique">
       <selector xpath="tns:entry"></selector>
       <field xpath="@name"></field>
       </unique>
    </element>
    <element name="websystem">
       <complexType>
           <sequence>
              <element ref="tns:servers" minOccurs="1" maxOccurs="unbounded"></element>
           </sequence>
       </complexType>
       <unique name="serversUnique">
       <selector xpath="tns:servers"></selector>
       <field xpath="@subject"></field>
       </unique>
    </element>
</schema>

=== yogreen/webcontent/src/META-INF/configs/websystem.xml
<?xml version="1.0" encoding="UTF-8"?>
<websystem xmlns="http://com.websystem.xml/schema" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://com.websystem.xml/schema schema.xsd ">
	<servers subject="serviceMessage">
		<multicast ip="231.0.0.1" port="5544" />
		<naming>
			<host master="true" name="n0Master" port="1973">192.168.1.105</host>
			<host name="n0Master_tcp" port="1974">192.168.1.103</host>
			<host name="n1" port="1974">192.168.1.105</host>
			<host name="n1_tcp" port="1975">192.168.1.105</host>
			<host name="n2Master" port="1976">192.168.1.103</host>
			<host name="n2_tcp" port="1977">192.168.1.105</host>
		</naming>
		<entry name="com.websystem.service.instance.WebsytemComputeInstance">
			<host master="true" name="eh0" port="3011">192.168.1.109</host>
			<host name="eh0_tcp" port="3013">192.168.1.105</host>
			<host name="eh1" port="3014">192.168.1.103</host>
			<host name="eh1_tcp" port="3015">192.168.1.108</host>
			<host name="eh2" port="3016">192.168.1.107</host>
			<host name="eh3_tcp" port="3017">192.168.1.105</host>
		</entry>
		
	</servers>

</websystem>
